# Shared constants and small helpers.
# shellcheck shell=bash

# Canonical process/env prefix is LESSPAPER_NGL_. Legacy FOLIUM_* is accepted for one cycle.
lesspaper_ngl_hydrate_legacy_env() {
  local new_key legacy_key pair
  local -a pairs=(
    LESSPAPER_NGL_GITHUB_REPO:FOLIUM_GITHUB_REPO
    LESSPAPER_NGL_GITHUB_URL:FOLIUM_GITHUB_URL
    LESSPAPER_NGL_APP_UID:FOLIUM_APP_UID
    LESSPAPER_NGL_APP_GID:FOLIUM_APP_GID
    LESSPAPER_NGL_DEFAULT_INSTALL_DIR:FOLIUM_DEFAULT_INSTALL_DIR
    LESSPAPER_NGL_DEFAULT_HTTP_PORT:FOLIUM_DEFAULT_HTTP_PORT
    LESSPAPER_NGL_DEFAULT_API_PORT:FOLIUM_DEFAULT_API_PORT
    LESSPAPER_NGL_DEFAULT_PROJECT:FOLIUM_DEFAULT_PROJECT
    LESSPAPER_NGL_PACKED:FOLIUM_PACKED
    LESSPAPER_NGL_NONINTERACTIVE:FOLIUM_NONINTERACTIVE
    LESSPAPER_NGL_KEEP_SECRETS:FOLIUM_KEEP_SECRETS
    LESSPAPER_NGL_JSON:FOLIUM_JSON
    LESSPAPER_NGL_MODE:FOLIUM_MODE
    LESSPAPER_NGL_UI:FOLIUM_UI
    LESSPAPER_NGL_INSTALL_DIR:FOLIUM_INSTALL_DIR
    LESSPAPER_NGL_VERSION:FOLIUM_VERSION
    LESSPAPER_NGL_VERSION_TAG:FOLIUM_VERSION_TAG
    LESSPAPER_NGL_METHOD:FOLIUM_METHOD
    LESSPAPER_NGL_BIND:FOLIUM_BIND
    LESSPAPER_NGL_HTTP_PORT:FOLIUM_HTTP_PORT
    LESSPAPER_NGL_API_PORT:FOLIUM_API_PORT
    LESSPAPER_NGL_EXPOSE_API:FOLIUM_EXPOSE_API
    LESSPAPER_NGL_FRONTEND_ORIGIN:FOLIUM_FRONTEND_ORIGIN
    LESSPAPER_NGL_DOCS_PATH:FOLIUM_DOCS_PATH
    LESSPAPER_NGL_CONSUME_PATH:FOLIUM_CONSUME_PATH
    LESSPAPER_NGL_EXPORT_PATH:FOLIUM_EXPORT_PATH
    LESSPAPER_NGL_PADDLE_PATH:FOLIUM_PADDLE_PATH
    LESSPAPER_NGL_EXTRA_GID:FOLIUM_EXTRA_GID
    LESSPAPER_NGL_COMPOSE_PROJECT:FOLIUM_COMPOSE_PROJECT
    LESSPAPER_NGL_STORAGE_KIND:FOLIUM_STORAGE_KIND
    LESSPAPER_NGL_SECRET_KEY:FOLIUM_SECRET_KEY
    LESSPAPER_NGL_ENCRYPTION_KEY:FOLIUM_ENCRYPTION_KEY
    LESSPAPER_NGL_ADMIN_USERNAME:FOLIUM_ADMIN_USERNAME
    LESSPAPER_NGL_ADMIN_PASSWORD:FOLIUM_ADMIN_PASSWORD
    LESSPAPER_NGL_LOG_FILE:FOLIUM_LOG_FILE
    LESSPAPER_NGL_SKIP_CLI:FOLIUM_SKIP_CLI
    LESSPAPER_NGL_ACCEPT_RISKY_PATH:FOLIUM_ACCEPT_RISKY_PATH
    LESSPAPER_NGL_RELEASE_COMPOSE_FILE:FOLIUM_RELEASE_COMPOSE_FILE
    LESSPAPER_NGL_HEALTH_RETRIES:FOLIUM_HEALTH_RETRIES
    LESSPAPER_NGL_HEALTH_SLEEP:FOLIUM_HEALTH_SLEEP
    LESSPAPER_NGL_SMOKE_DIR:FOLIUM_SMOKE_DIR
    LESSPAPER_NGL_SMOKE_KEEP:FOLIUM_SMOKE_KEEP
  )
  for pair in "${pairs[@]}"; do
    new_key="${pair%%:*}"
    legacy_key="${pair#*:}"
    if [[ -z "${!new_key:-}" && -n "${!legacy_key:-}" ]]; then
      printf -v "${new_key}" '%s' "${!legacy_key}"
      export "${new_key?}"
    fi
  done
  if [[ -z "${LESSPAPER_NGL_FRONTEND_ORIGIN:-}" && -n "${FRONTEND_ORIGIN:-}" ]]; then
    LESSPAPER_NGL_FRONTEND_ORIGIN="${FRONTEND_ORIGIN}"
    export LESSPAPER_NGL_FRONTEND_ORIGIN
  fi
  if [[ -z "${LESSPAPER_NGL_COMPOSE_PROJECT:-}" && -n "${COMPOSE_PROJECT_NAME:-}" ]]; then
    LESSPAPER_NGL_COMPOSE_PROJECT="${COMPOSE_PROJECT_NAME}"
    export LESSPAPER_NGL_COMPOSE_PROJECT
  fi
}

lesspaper_ngl_hydrate_legacy_env

LESSPAPER_NGL_GITHUB_REPO="${LESSPAPER_NGL_GITHUB_REPO:-brocxftw/lesspaper-ngl}"
LESSPAPER_NGL_GITHUB_URL="${LESSPAPER_NGL_GITHUB_URL:-https://github.com/${LESSPAPER_NGL_GITHUB_REPO}}"
LESSPAPER_NGL_APP_UID="${LESSPAPER_NGL_APP_UID:-1000}"
LESSPAPER_NGL_APP_GID="${LESSPAPER_NGL_APP_GID:-1000}"
LESSPAPER_NGL_DEFAULT_INSTALL_DIR="${LESSPAPER_NGL_DEFAULT_INSTALL_DIR:-/opt/lesspaper-ngl}"
LESSPAPER_NGL_DEFAULT_HTTP_PORT="${LESSPAPER_NGL_DEFAULT_HTTP_PORT:-9398}"
LESSPAPER_NGL_DEFAULT_API_PORT="${LESSPAPER_NGL_DEFAULT_API_PORT:-9099}"
LESSPAPER_NGL_DEFAULT_PROJECT="${LESSPAPER_NGL_DEFAULT_PROJECT:-lesspaper-ngl}"

is_root() {
  [[ "$(id -u)" -eq 0 ]]
}

run_root() {
  if is_root; then
    "$@"
  else
    sudo "$@"
  fi
}

require_cmd() {
  local name="$1"
  command -v "${name}" >/dev/null 2>&1
}

is_amd64() {
  local m
  m="$(uname -m)"
  [[ "${m}" == "x86_64" || "${m}" == "amd64" ]]
}

config_strip_v_prefix() {
  local v="${1:-}"
  v="${v#v}"
  printf '%s' "${v}"
}

config_is_pinned_version() {
  local v="${1:-}"
  v="$(config_strip_v_prefix "${v}")"
  [[ "${v}" =~ ^[0-9]+\.[0-9]+\.[0-9]+([+.-][A-Za-z0-9.-]+)?$ ]]
}

json_get() {
  python3 -c 'import json,sys; data=json.load(sys.stdin); path=sys.argv[1].split(".");
cur=data
for p in path:
    cur=cur[p]
if isinstance(cur,(dict,list)):
    json.dump(cur,sys.stdout)
else:
    print(cur, end="")
' "$1"
}
