#!/usr/bin/env bash
# Concatenate the modular installer into one standalone script for GitHub Releases.
# Usage: pack.sh [outfile]
#   outfile defaults to stdout.
#   When outfile basename is install-lesspaper-ngl.sh, also write install-folium.sh alongside.
# shellcheck disable=SC2016
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${1:-}"

INSTALL_LIBS=(
  lib/common.sh
  lib/logging.sh
  lib/ui.sh
  lib/state.sh
  lib/system.sh
  lib/docker.sh
  lib/dependencies.sh
  lib/storage.sh
  lib/network.sh
  lib/config.sh
  lib/health.sh
)

CTL_LIBS=(
  lib/common.sh
  lib/logging.sh
  lib/docker.sh
  lib/system.sh
  lib/storage.sh
  lib/network.sh
  lib/state.sh
  lib/health.sh
  lib/ctl_update.sh
)

emit_lib() {
  local rel="$1"
  printf '\n# ---- %s ----\n' "${rel}"
  # Drop shebang if present; keep shellcheck directives.
  sed '/^#!/d' "${ROOT}/${rel}"
  printf '\n'
}

pack_ctl() {
  cat <<'HDR'
#!/usr/bin/env bash
# Generated by installer/pack.sh — lesspaper-ngl management CLI.
set -euo pipefail
LESSPAPER_NGL_PACKED=1
HDR
  local rel
  for rel in "${CTL_LIBS[@]}"; do
    emit_lib "${rel}"
  done
  sed '/^#!/d' "${ROOT}/lesspaper-ngl-ctl.sh"
}

pack_installer() {
  cat <<'HDR'
#!/usr/bin/env bash
# Generated by installer/pack.sh — standalone lesspaper-ngl installer.
# Source lives in installer/{install.sh,lib,lesspaper-ngl-ctl.sh}. Do not edit this file.
set -euo pipefail
LESSPAPER_NGL_PACKED=1
HDR
  local rel
  for rel in "${INSTALL_LIBS[@]}"; do
    emit_lib "${rel}"
  done

  printf '\nlesspaper_ngl_install_packed_ctl() {\n'
  printf '  local tmp shim\n'
  printf '  tmp="$(mktemp)"\n'
  printf "  cat >\"\${tmp}\" <<'LESSPAPER_NGL_PACKED_CTL_EOF'\n"
  pack_ctl
  printf 'LESSPAPER_NGL_PACKED_CTL_EOF\n'
  cat <<'FOOT'
  chmod 700 "${tmp}"
  mkdir -p "${LESSPAPER_NGL_INSTALL_DIR}/installer"
  cp -a "${tmp}" "${LESSPAPER_NGL_INSTALL_DIR}/installer/lesspaper-ngl"
  run_root install -m 755 "${tmp}" /usr/local/bin/lesspaper-ngl
  # Compat shim: /usr/local/bin/folium → lesspaper-ngl
  shim="$(mktemp)"
  cat >"${shim}" <<'SHIM'
#!/usr/bin/env bash
exec /usr/local/bin/lesspaper-ngl "$@"
SHIM
  chmod 755 "${shim}"
  cp -a "${shim}" "${LESSPAPER_NGL_INSTALL_DIR}/installer/folium"
  run_root install -m 755 "${shim}" /usr/local/bin/folium
  rm -f "${tmp}" "${shim}"
}
FOOT

  printf '\n# ---- install.sh ----\n'
  sed '/^#!/d' "${ROOT}/install.sh"
}

if [[ -n "${OUT}" ]]; then
  pack_installer >"${OUT}"
  chmod 755 "${OUT}"
  base="$(basename "${OUT}")"
  dir="$(dirname "${OUT}")"
  if [[ "${base}" == "install-lesspaper-ngl.sh" ]]; then
    cp -a "${OUT}" "${dir}/install-folium.sh"
    chmod 755 "${dir}/install-folium.sh"
  fi
else
  pack_installer
fi
